In [3]:
lst = [1,2,3,4,5,6,7,8,9,0]

print(lst)
print(type(lst))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
<class 'list'>


In [3]:
!pip install numpy

In [2]:
import numpy as np

In [5]:
arr = np.array(lst)

In [6]:
print(arr)

[1 2 3 4 5 6 7 8 9 0]


In [7]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [22]:
print(type(arr))

<class 'numpy.ndarray'>


In [30]:
lst1 = [1,2,3,4,5]
lst2 = [6,7,8,9,10]
lst3 = [11,12,13,14,15]

print(lst1,lst2,lst3)

[1, 2, 3, 4, 5] [6, 7, 8, 9, 10] [11, 12, 13, 14, 15]


In [31]:
arr1 = np.array([lst1,lst2,lst3])

In [33]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [34]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [36]:
arr1.shape     # (Rows,columns)

(3, 5)

### Creating array

In [40]:
                  # (start vaule,end value) end value n-1
c_arr =  np.arange(1,25).reshape(6,4)      

In [41]:
c_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [43]:
arr_ = np.arange(0,26).reshape(2,13)

In [44]:
arr_

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [ ]:
# task

In [48]:
arr_name = np.arange(1,47).reshape(2,23)

In [49]:
arr_name

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
        40, 41, 42, 43, 44, 45, 46]])

In [8]:
arr__count=np.arange(1,64).reshape(9,7)

In [9]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [10]:
arr__count[[5][1:5],[6][1:5],[7][1:5]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [54]:
arr__count[4:7,1:6]  # row start value : end value , column start value:end value

array([[30, 31, 32, 33, 34],
       [37, 38, 39, 40, 41],
       [44, 45, 46, 47, 48]])

In [55]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [58]:
# 47 48 49
# 54 55 56
# 61 62 63

arr__count[6:,4:]

array([[47, 48, 49],
       [54, 55, 56],
       [61, 62, 63]])

In [59]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [61]:
# 25 26 27
# 32 33 34

arr__count[3:5,3:6]

array([[25, 26],
       [32, 33]])

In [62]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [ ]:
#            0   1  2   3   4   5  6
#           |   |   |   |   |   |  |
# array([[ 1,  2,  3,  4,  5,  6,  7], -> 0
#        [ 8,  9, 10, 11, 12, 13, 14], -> 1
#        [15, 16, 17, 18, 19, 20, 21], -> 2
#        [22, 23, 24, 25, 26, 27, 28], -> 3
#        [29, 30, 31, 32, 33, 34, 35], -> 4
#        [36, 37, 38, 39, 40, 41, 42], -> 5
#        [43, 44, 45, 46, 47, 48, 49],  -> 6
#        [50, 51, 52, 53, 54, 55, 56],  -> 7
#        [57, 58, 59, 60, 61, 62, 63]])  -> 8

In [ ]:
# [29,30,31,32,33,34,35]  -> 4 
# [36,37,38,39,40,41,42]   -> 5

In [64]:
# 31 32 33 
# 38 39 40

arr__count[4:6,2:5]  # row start vaule : end value (end n-1) , column start value : end value (n-1)

array([[31, 32, 33],
       [38, 39, 40]])

In [11]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [13]:
arr__count[5]

array([36, 37, 38, 39, 40, 41, 42])

In [14]:
arr__count[5,2]

np.int64(38)

### Practical

In [15]:
arr__count

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63]])

In [17]:
arr__count[arr__count>=30]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [18]:
arr__count[arr__count%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

In [19]:
arr__count[arr__count%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63])

In [20]:
arr__count.shape

(9, 7)

In [21]:
arr__ = np.arange(0,10).reshape(2,5)
arr__

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
arr__1 = np.arange(11,21).reshape(2,5)
arr__1

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
arr__+arr__1

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29]])

In [28]:
arr__*arr__1

array([[  0,  12,  26,  42,  60],
       [ 80, 102, 126, 152, 180]])

### Ones and zeros

In [31]:
np.ones((5,5),dtype=int,) # dtype ->datatype

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.zeros((5,5),dtype=int,) # dtype ->datatype

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [120]:
np.zeros(8,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0])

### Random distribution

In [39]:
np.random.rand(4,4)

array([[0.09565477, 0.61538135, 0.65212441, 0.6233383 ],
       [0.99830447, 0.68130448, 0.09907303, 0.40681451],
       [0.28308432, 0.90054992, 0.01716268, 0.44390986],
       [0.20847344, 0.00788563, 0.94553109, 0.3167931 ]])

In [42]:
np.random.randn(4,4)

array([[-0.11498977,  0.76019042, -0.88061596,  0.13396942],
       [ 0.69036703,  1.10329848,  0.77219589, -0.03003225],
       [ 0.23288998,  0.59867208,  0.176194  , -1.49123587],
       [ 0.73746024,  0.9136596 ,  1.49017419, -1.04319558]])

In [48]:
np.random.random_sample((4,4))

array([[0.70517608, 0.57891541, 0.68109994, 0.3730087 ],
       [0.95506399, 0.64578525, 0.11085013, 0.06322494],
       [0.2322219 , 0.24379169, 0.90372333, 0.70748344],
       [0.64628729, 0.17994758, 0.96717518, 0.24664748]])

In [7]:
np.random.randint(1,40,16).reshape(4,4)  # (start value,end value,array size)

array([[ 2, 12,  1, 35],
       [20, 33, 31, 16],
       [18, 36, 35, 28],
       [20, 22, 27, 38]], dtype=int32)

In [64]:
np.random.uniform(1,50,18).reshape(6,3)

array([[35.88313157, 16.00733152, 23.22045856],
       [22.33899196, 10.58516038, 28.63622712],
       [ 3.26470919, 46.18020442,  3.19895825],
       [ 1.2480331 ,  4.4128054 , 11.80945509],
       [35.00778772, 45.95808262, 42.68975975],
       [12.74757326, 13.68571618, 18.91264487]])

In [8]:
np.random.binomial(n=10,p=0.8,size = 10)

array([ 7,  7,  9,  8,  8,  6, 10,  6,  8,  9], dtype=int32)

In [103]:
arr_r = np.array([10,20,30,40,50])
arr_r

array([10, 20, 30, 40, 50])

In [113]:
np.random.shuffle(arr_r)
arr_r

array([30, 50, 20, 40, 10])

### Even spacing

In [125]:
np.linspace(1,10,6,dtype=int)

array([ 1,  2,  4,  6,  8, 10])

In [127]:
a = np.array([1,2,3,4,5,6,7,8,9,0])

In [128]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [129]:
np.sum(a)

np.int64(45)

In [130]:
np.min(a)

np.int64(0)

In [131]:
np.max(a)

np.int64(9)

In [136]:
np.mean(a)

np.float64(4.5)

In [133]:
np.std(a)

np.float64(2.8722813232690143)

### Pratical adv

In [137]:
a_1 = np.array([5,7,9,13,15])
d1 = 6

print(a_1+d1)

[11 13 15 19 21]


### Horizontal stack and veritcal stack

In [139]:
a_1 = np.array([5,7,9,13,15])
a_2 = np.array([11,13,16,19,21])

np.vstack((a_1,a_2))

array([[ 5,  7,  9, 13, 15],
       [11, 13, 16, 19, 21]])

In [140]:
np.hstack((a_1,a_2))

array([ 5,  7,  9, 13, 15, 11, 13, 16, 19, 21])

### Splitting

In [144]:
a_3 = np.array([1,2,3,4,5,6])
a_3

array([1, 2, 3, 4, 5, 6])

In [146]:
np.split(a_3,2)

[array([1, 2, 3]), array([4, 5, 6])]

### Sorting

In [148]:
a_4 = np.array([55,19,8,15,76,5])
a_4

array([55, 19,  8, 15, 76,  5])

In [151]:
np.sort(a_4) # ascending

array([ 5,  8, 15, 19, 55, 76])

In [150]:
np.sort(a_4)[::-1] # descending

array([76, 55, 19, 15,  8,  5])

In [152]:
-np.sort(-a_4)

array([76, 55, 19, 15,  8,  5])

In [153]:
a_4

array([55, 19,  8, 15, 76,  5])

In [156]:
np.where(a_4 == 76)

(array([4]),)

In [159]:
a_4[4]

np.int64(76)

In [157]:
dup = np.array([7,5,11,5,14,9,13,7])
dup

array([ 7,  5, 11,  5, 14,  9, 13,  7])

In [158]:
np.unique(dup)

array([ 5,  7,  9, 11, 13, 14])

In [161]:
np.save("numpy_data.npy",dup)

In [166]:
# np.save("numpy.csv",dup)

In [162]:
arr_dup = np.load("numpy_data.npy")

In [163]:
arr_dup

array([ 7,  5, 11,  5, 14,  9, 13,  7])

In [169]:
# data = np.loadtxt("numpy.csv",delimiter=",")

In [170]:
!pip install pandas

In [171]:
import pandas as pd

In [ ]:
### CSV -> Comma Seperated Values

In [172]:
df = pd.read_csv("banana_quality.csv")

In [173]:
df

Size    Weight  Sweetness  Softness  HarvestTime  Ripeness  \
0    -1.924968  0.468078   3.077832 -1.472177     0.294799  2.435570   
1    -2.409751  0.486870   0.346921 -2.495099    -0.892213  2.067549   
2    -0.357607  1.483176   1.568452 -2.645145    -0.647267  3.090643   
3    -0.868524  1.566201   1.889605 -1.273761    -1.006278  1.873001   
4     0.651825  1.319199  -0.022459 -1.209709    -1.430692  1.078345   
...        ...       ...        ...       ...          ...       ...   
7995 -6.414403  0.723565   1.134953  2.952763     0.297928 -0.156946   
7996  0.851143 -2.217875  -2.812175  0.489249    -1.323410 -2.316883   
7997  1.422722 -1.907665  -2.532364  0.964976    -0.562375 -1.834765   
7998 -2.131904 -2.742600  -1.008029  2.126946    -0.802632 -3.580266   
7999 -2.660879 -2.044666   0.159026  1.499706    -1.581856 -1.605859   

       Acidity Quality  
0     0.271290    Good  
1     0.307325    Good  
2     1.427322    Good  
3     0.477862    Good  
4     2.812442    Good  
...        ...     ...  
7995  2.398091     Bad  
7996  2.113136     Bad  
7997  0.697361     Bad  
7998  0.423569     Bad  
7999  1.435644     Bad  

[8000 rows x 8 columns]

In [174]:
df.shape

(8000, 8)

In [175]:
arr = df.loc[4]
arr

Size           0.651825
Weight         1.319199
Sweetness     -0.022459
Softness      -1.209709
HarvestTime   -1.430692
Ripeness       1.078345
Acidity        2.812442
Quality            Good
Name: 4, dtype: object

In [176]:
arr1 = df.loc[3]
arr1

Size          -0.868524
Weight         1.566201
Sweetness      1.889605
Softness      -1.273761
HarvestTime   -1.006278
Ripeness       1.873001
Acidity        0.477862
Quality            Good
Name: 3, dtype: object

In [177]:
arr+arr1

Size          -0.216698
Weight         2.885401
Sweetness      1.867146
Softness       -2.48347
HarvestTime    -2.43697
Ripeness       2.951347
Acidity        3.290304
Quality        GoodGood
dtype: object

In [178]:
arr_n = arr.to_numpy()

In [179]:
arr_n

array([np.float64(0.65182525), np.float64(1.3191992),
       np.float64(-0.022458995), np.float64(-1.2097088),
       np.float64(-1.430692), np.float64(1.0783454),
       np.float64(2.8124418), 'Good'], dtype=object)

In [9]:
checkon = np.array([9,8,7,6,5,4,3,2,1])
checkon

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [10]:
checkon[checkon>=5]

array([9, 8, 7, 6, 5])

In [13]:
checkon[checkon % 2 ==1]

array([9, 7, 5, 3, 1])